_commit: v1.9.0-1-g02b6330
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: intel-device-plugins-gpu
helmRelease: intel-device-plugins-gpu
helmRepo: https://intel.github.io/helm-charts/
helmValues: helm/values.yaml
helmVersion: ''
homepageEnabled: false
ingress: false
labels: ''
name: intel-device-plugins-gpu
namespace: intel-device-plugins-gpu
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://intel.github.io/intel-device-plugins-for-kubernetes/cmd/gpu_plugin/README.html
url: https://github.com/charlesthomas/homelab-intel-device-plugins-gpu
