---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-device-plugins-gpu

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-intel-device-plugins-gpu

resources:
- resources/namespaces.yaml
- resources/gpu-device-plugin.yaml
- resources/node-feature-rules.yaml
