---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-device-plugins-gpu

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-intel-device-plugins-gpu

resources:
- resources/namespaces.yaml
helmCharts:
- name: intel-device-plugins-gpu
  namespace: intel
  releaseName: intel-device-plugins-gpu
  repo: https://intel.github.io/helm-charts/
  valuesFile: helm/values.yaml
